const data =  {
    products:[
        {
        _id: '1',
        name:'Indian Tabla',
        category:'Hindustani',
        image:'https://images-na.ssl-images-amazon.com/images/I/51IA6CWhjRL._SX355_.jpg',
        price: 10000,
        brand: 'Meinl',
        rating: "4.1",
        countInstock : 4, 
    }, 
    {
        _id: '2',
        name:'Indian Flute',
        category:'Hindustani',
        image:'https://5.imimg.com/data5/QV/CW/MY-35196954/musical-flute-500x500.jpg',
        price: 5000,
        brand: 'Punam',
        rating: "3.9",
        countInstock : 6, 
    }, 
    {
        _id: '3',
        name:'Piano',
        category:'Western',
        image:'https://images-na.ssl-images-amazon.com/images/I/41qyq2w4TcL._AC_SX466_.jpg',
        price: 130000,
        brand: 'Yamaha',
        rating: "4.7",
        countInstock : 7, 
    }, 
    {
        _id: '4',
        name:'Harmonica',
        category:'Western',
        image:'https://images-na.ssl-images-amazon.com/images/I/61-cGav9qTL._AC_SL1000_.jpg',
        price: 3000,
        brand: 'Hohner',
        rating: "4.32",
        countInstock : 6, 
    },
    {
        _id: '5',
        name:'Bass Guitar',
        category:'Guitars',
        image:'https://images-na.ssl-images-amazon.com/images/I/51ai2l6OlKL._SL1000_.jpg',
        price: 40000,
        brand: 'PRS',
        rating: "3.56",
        countInstock : 6, 
    }, 
    {
        _id: '6',
        name:'Stratocaster Electric Guitar',
        category:'Guitars',
        image:'https://media.sweetwater.com/api/i/q-82__ha-6586103121883da8__hmac-ed6bfebeb563889032e8581b743cce51b050b502/images/items/750/Strat59HvCAR-large.jpg',
        price: 60000,
        brand: 'Fender',
        rating: "4.98",
        countInstock : 7, 
    }, 
    {
        _id: '7',
        name:'Les Paul Electric Guitar',
        category:'Guitars',
        image:'https://sc1.musik-produktiv.com/pic-010109188xl/gibson-les-paul-standard-heritage-cherry-sunburst-10109188.jpg',
        price: 80000,
        brand: 'Gibson',
        rating: "4.78",
        countInstock : 8, 
    },
    {
        _id: '8',
        name:'C-200 Keyboard',
        category:'Western',
        image:'https://m.media-amazon.com/images/I/81jzju4YMxL._AC_SS350_.jpg',
        price: 40000,
        brand: 'Korg',
        rating: "4.12",
        countInstock : 11, 
    },
    {
        _id: '9',
        name:'Drum Kit',
        category:'Western',
        image:'https://i.pinimg.com/originals/1a/f4/08/1af4083bd799bfc826759254d88833d1.jpg',
        price: 45000,
        brand: 'Pearl',
        rating: "3.73",
        countInstock : 12, 
    }, 
    {
        _id: '10',
        name:'Sitar',
        category:'Hindustani',
        image:'https://images-na.ssl-images-amazon.com/images/I/8193tHXsaFL._SL1500_.jpg',
        price: 20000,
        brand: 'Maharaja',
        rating: "4.64",
        countInstock : 4, 
    },
    {
        _id: '11',
        name:'Harmonium',
        category:'Hindustani',
        image:'https://5.imimg.com/data5/BM/RB/UF/SELLER-4881839/regular-harmonium-500x500.jpg',
        price: 30000,
        brand: 'Naskar',
        rating: "4.37",
        countInstock : 12, 
    },
    {
        _id: '12',
        name:'Violin',
        category:'Western',
        image:'https://www.wollongongmusic.com.au/ProdImages/paganini-500-series-student-violin-outfits-1.jpg',
        price: 325000,
        brand: 'Paganini',
        rating: "2.57",
        countInstock : 3, 
    },
    {
        _id: '12',
        name:'Guitar Amplifier',
        category:'Guitars',
        image:'https://images-na.ssl-images-amazon.com/images/I/91BsprGfb5L._SL1500_.jpg',
        price: 15000,
        brand: 'Blackstar',
        rating: "3.81",
        countInstock : 10, 
    }
]
}

module.exports = data;